#caminho padrão
path_default:
  /login-form
# configurações de conexão ao banco de dados
connection:
  host: localhost
  name: ..\tads.db
  user: root
  pass:
  type: sql
# caminhos desprotegidos definidos por expressões regulares
paths_unprotected:
  - /login/
  - /404found/
# caminho seguido quando é acessado um sem permissão
path_unprotected_default:
  /login-form
# caminho seguido quando é acessado um inexistente
path_not_found:
  /404found
# namespace para controladores
path_controller:
  \Ifnc\Tads\Controller\
