#Configuração de rotas
/portal: PortalController
/login-form: LoginFormController
/login: LoginController
/Pagina-inicial: PaginaInicialController
/logout:  LogoutController
/404found:  path404Controller
/cadastro-form: cadastroFormController
/cadastrar: loginCadastrarController
/verificar-form: verificarFormController
/verificar: verificarController