#Configuração de rotas
/portal: PortalController
/login-form: LoginFormController
/login: LoginController
/Pagina-inicial: PaginaInicialController
/logout:  LogoutController
/404found:  path404Controller
/recuperar-senha: RecuperarSenharFormController
/recuperar: RecuperarSenhaController
/boletim: BoletimController
/perfil: PerfilController
/perfil-funcionario: PerfilFuncionarioController
/update-perfil: UpdatePerfilController
/update-perfilf: UpdatePerfilFuncionarioController
/primeiro-login: PrimeiroLoginFormController
/primeroLogin: PrimeiroLoginController
/cadastro-form: CadastroFormController
/cadastrar: CadastroController
/matricular: MatricularController
/consultar: ConsultarController
/turmas: TurmasController
/disciplinas: DisciplinasController
/disciplinas-aluno: DisciplinasAlunoController
/cadastrar-turma: CadastroTurmaController
/cadastrar-disciplina: CadastroDisciplinaController
/email: EmailController
/solicitacao: SolicitacaoController
/solicitacoes: SolicitacoesController
/vincular-aluno: DisciplinaAlunoController
/disciplina-alunos: VincularAlunoController
/disciplinas-professor: DisciplinasProfessorController
/update-perfil-consulta: UpdatePerfilConsultaController
/update-perfil-consulta-funcionario: UpdatePerfilConsultaFuncionarioController
/inative-funcionario: InativeFuncionarioController
/imprimir-boletim: ImprimirBoletimController
/imprimir-boletim-funcionario: ImprimirBoletimFuncionarioController
/imprimir-dvinculo: ImprimirVinculoController
/imprimir-dfrequencia: ImprimirFrequenciaController
/imprimir-dhistorico: ImprimirHistoricoController
/lista-turmas: ListaTurmasController
/listar-turmas: ListarTurmasController
/inserir-notas: InserirNotasFormController
/inserir-frequencia: InserirFrequenciaFormController
/update-notas: InserirNotasController
/update-frequencia: InserirFrequenciasController
/declaracoes: DeclaracoesController
/vizualizar-turma: VizualizarTurmasController
/turmas-professor: TurmasProfessorController
/detalhar-turma: DetalharTurmaController
/list-team: ListTeamController
/deletar-disciplina: DeletarDisciplinaController