#Configuração de rotas
/portal: PortalController
/login-form: LoginFormController
/login: LoginController
/Pagina-inicial: PaginaInicialController
/logout:  LogoutController
/404found:  path404Controller
/verificar-form: verificarFormController
/verificar: verificarController
/boletim: boletimController
/perfil: perfilController
/update-aluno: updateAlunoController