#Configuração de rotas
/portal: PortalController
/login-form: LoginFormController
/login: LoginController
/Pagina-inicial: PaginaInicialController
/logout:  LogoutController
/404found:  path404Controller
/recuperar-senha: RecuperarSenharFormController
/recuperar: RecuperarSenhaController
/boletim: BoletimController
/perfil: PerfilController
/perfil-funcionario: PerfilFuncionarioController
/update-perfil: UpdatePerfilController
/primeiro-login: PrimeiroLoginFormController
/primeroLogin: PrimeiroLoginController
/cadastro-form: CadastroFormController
/cadastrar: CadastroController
/matricular: MatricularController
/consultar: ConsultarController
/turmas: TurmasController
/disciplinas: DisciplinasController
/disciplinas-aluno: DisciplinasAlunoController
/cadastrar-turma: CadastroTurmaController
/cadastrar-disciplina: CadastroDisciplinaController
/email: EmailController
/solicitacao: SolicitacaoController
/solicitacoes: SolicitacoesController
/vincular-aluno: DisciplinaAlunoController
/disciplina-alunos: VincularAlunoController
/disciplinas-professor: DisciplinasProfessorController
/update-perfil-consulta: UpdatePerfilConsultaController
/update-perfil-consulta-funcionario: UpdatePerfilConsultaFuncionarioController
/inative-funcionario: InativeFuncionarioController
/imprimir-boletim: ImprimirBoletimController
/lista-turmas: ListarTurmasController
/inserir-notas: InserirNotasController
