#Configuração de rotas
/portal: PortalController
/login-form: LoginFormController
/login: LoginController
/Pagina-inicial: PaginaInicialController
/logout:  LogoutController
/404found:  path404Controller
/recuperar-senha: RecuperarSenharFormController
/recuperar: RecuperarSenhaController
/boletim: BoletimController
/perfil: PerfilController
/perfil-funcionario: PerfilFuncionarioController
/update-aluno: UpdateAlunoController
/update-perfil: UpdatePerfilController
/primeiro-login: PrimeiroLoginFormController
/primeroLogin: PrimeiroLoginController
/cadastro-form: CadastroFormController
/cadastrar: CadastroController
/matricular: MatricularController
/consultar: ConsultarController
/turmas: TurmasController
/cadastrar-turma: CadastroTurmaController
/email: EmailController