#Configuração de rotas
/portal: PortalController
/login-form: LoginFormController
/login: LoginController
/Pagina-inicial: PaginaInicialController
/logout:  LogoutController
/404found:  path404Controller
/recuperar-senha: RecuperarSenharFormController
/recuperar: RecuperarSenhaController
/boletim: BoletimController
/perfil: PerfilController
/update-aluno: UpdateAlunoController
/update-perfil: UpdatePerfilController
/primeiro-login: PrimeiroLoginFormController
/primeroLogin: PrimeiroLoginController