#Configuração de rotas
/portal: PortalController
/login-form: LoginFormController
/login: LoginController
/Pagina-inicial: PaginaInicialController
/logout:  LogoutController
/404found:  path404Controller
/form-cadastro: cadastroFormController
/cadastrar: loginCadastrarController
/form-verificar: verificarFormController
/verificar: verificarCadastroController